sudo: required
services:
  - docker

before_install:
  - docker build -t sujono91/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sujono91/react-test npm test -- --coverage

after_success:
  - docker build -t sujono91/multi-client ./client
  - docker build -t sujono91/multi-nginx ./nginx
  - docker build -t sujono91/multi-server ./server
  - docker build -t sujono91/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push those images to docker hub
  - docker push sujono91/multi-client
  - docker push sujono91/multi-nginx
  - docker push sujono91/multi-server
  - docker push sujono91/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-254034606437"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY